#!/usr/bin/env python3
"""KTC Mail — mail stack configuration renderer.

Phase 3 deliverable. Takes a SetupProfile and generates working
Postfix, Dovecot, Rspamd, and Nginx configuration files.

This is the module that actually makes this a mail server instead
of just a DNS setup wizard. Every template is a function that takes
a SetupProfile and returns a config string. No side effects in the
render functions — the caller decides where to write.

Design rules:
  - Templates produce VALID config for Debian/Ubuntu packages
  - TLS is mandatory everywhere (STARTTLS on 25/587, TLS on 465/993)
  - Rspamd milter is inline (not proxy) — reject at SMTP time
  - Virtual mailboxes via Dovecot LMTP, stored in /var/mail/%d/%n
"""

from __future__ import annotations

import argparse
import base64
import os
import subprocess
import sys
from pathlib import Path
from typing import Any

from .config import (
    CONFIG_DIR,
    SETUP_PATH,
    SetupProfile,
    SecurityPolicy,
    read_json,
)


# ── Main.cf template ───────────────────────────────────────────────────────


def render_postfix_main_cf(profile: SetupProfile) -> str:
    """Generate /etc/postfix/main.cf from a SetupProfile.

    Produces a config that is:
      - Chrooted (Debian default)
      - TLS everywhere (25/465/587 all enforce TLS)
      - Rspamd milter for spam/virus filtering
      - Postscreen for pre-queue zombie blocking
      - Rate-limited via anvil
      - Virtual domains from the profile
    """
    hostname = profile.hostname
    mynetworks = ["127.0.0.0/8", "[::ffff:127.0.0.0]/104", "[::1]/128"]
    if profile.public_ipv4:
        mynetworks.append(profile.public_ipv4 + "/32")

    lines = [
        "# KTC Mail — Postfix main.cf",
        "# Generated by ktc-mail config-renderer. DO NOT EDIT MANUALLY.",
        f"# Source: {profile.domain} via {__file__}",
        "",
        "# ── Base identity ────────────────────────────────────────────",
        f"myhostname = {hostname}",
        f"mydomain = {profile.domain}",
        f"myorigin = $mydomain",
        f"mydestination = $myhostname, localhost.$mydomain, localhost",
        f"relay_domains = $mydomain",
        "",
        "# ── Networks ────────────────────────────────────────────────",
        f"mynetworks = {' '.join(mynetworks)}",
        f"inet_interfaces = all",
        f"inet_protocols = {'all' if profile.has_ipv6 else 'ipv4'}",
        "",
        "# ── TLS (enforced everywhere) ───────────────────────────────",
        "smtpd_tls_security_level = may",
        "smtpd_tls_auth_only = yes",
        "smtpd_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1",
        "smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1",
        "smtpd_tls_mandatory_ciphers = high",
        "smtpd_tls_eecdh_grade = strong",
        "smtpd_tls_key_file = /etc/letsencrypt/live/ktc-mail/privkey.pem",
        "smtpd_tls_cert_file = /etc/letsencrypt/live/ktc-mail/fullchain.pem",
        "smtpd_tls_CAfile = /etc/letsencrypt/live/ktc-mail/chain.pem",
        "smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache",
        "smtpd_tls_received_header = yes",
        "",
        "smtp_tls_security_level = may",
        "smtp_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1",
        "smtp_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1",
        "smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache",
        "",
        "# ── SASL auth (via Dovecot) ────────────────────────────────",
        "smtpd_sasl_type = dovecot",
        "smtpd_sasl_path = private/auth",
        "smtpd_sasl_auth_enable = yes",
        "smtpd_sasl_security_options = noanonymous",
        "smtpd_sasl_tls_security_options = noanonymous",
        "broken_sasl_auth_clients = yes",
        "",
        "# ── Rspamd milter ──────────────────────────────────────────",
        "smtpd_milters = inet:localhost:11332",
        "non_smtpd_milters = inet:localhost:11332",
        "milter_protocol = 6",
        "milter_mail_macros = i {mail_addr} {client_addr} {client_name} {auth_authen}",
        "milter_default_action = accept",
        "",
        "# ── Postscreen (pre-queue filtering) ───────────────────────",
        "postscreen_access_list = permit_mynetworks",
        "postscreen_dnsbl_sites = zen.spamhaus.org, bl.mailspike.net, b.barracudacentral.org",
        "postscreen_dnsbl_threshold = 3",
        "postscreen_greet_action = enforce",
        "postscreen_bare_newline_action = enforce",
        "postscreen_non_smtp_command_action = enforce",
        "postscreen_pipelining_action = enforce",
        "",
        "# ── Rate limits (anvil) ────────────────────────────────────",
        "anvil_rate_time_unit = 60s",
        "smtpd_client_connection_rate_limit = 30",
        "smtpd_client_connection_count_limit = 10",
        "smtpd_client_message_rate_limit = 60",
        "smtpd_client_recipient_rate_limit = 60",
        "smtpd_client_event_limit_exceptions = ${mynetworks}",
        "",
        "# ── Restrictions ───────────────────────────────────────────",
        "smtpd_helo_required = yes",
        "disable_vrfy_command = yes",
        "strict_rfc821_envelopes = yes",
        "",
        "# Relay control: Postfix 3.7+ requires this or smtpd_recipient_restrictions",
        "# to have at least reject_unauth_destination — without it smtpd refuses to start.",
        "smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination",
        "",
        "# ── Queue ───────────────────────────────────────────────────",
        "maximal_queue_lifetime = 4d",
        "bounce_queue_lifetime = 4d",
        "minimal_backoff_time = 300s",
        "maximal_backoff_time = 3600s",
        "queue_run_delay = 300s",
        "",
        "# ── Delivery ─────────────────────────────────────────────────",
        "default_transport = smtp",
        "relay_transport = relay",
        "# Virtual domain delivery via Dovecot LMTP",
        "virtual_transport = lmtp:unix:private/dovecot-lmtp",
        "virtual_mailbox_domains = $mydomain",
        # Virtual alias and mailbox maps: Postfix queries these to
        # decide whether a recipient is valid. Dovecot handles the
        # actual storage. The maps are managed by ktc-mail later.
        "virtual_alias_maps = texthash:/etc/postfix/virtual_alias",
        "virtual_mailbox_maps = texthash:/etc/postfix/virtual_mbx",
        "",
        "# ── Message size ────────────────────────────────────────────",
        "message_size_limit = 25600000",
        "mailbox_size_limit = 0",
        "",
    ]
    return "\n".join(lines) + "\n"


def render_postfix_master_cf(profile: SetupProfile) -> str:
    """Generate /etc/postfix/master.cf.

    Defines the smtpd, submission (587), and smtps (465) services.
    Postscreen runs before smtpd as the first line of defence.
    """
    lines = [
        "# KTC Mail — Postfix master.cf",
        "# Generated by ktc-mail config-renderer. DO NOT EDIT MANUALLY.",
        "",
        "# ── SMTP (port 25, with postscreen) ───────────────────────",
        "smtp      inet  n       -       n       -       -       smtpd",
        "  -o syslog_name=postfix/smtpd",
        "  -o smtpd_tls_security_level=may",
        "",
        "# ── Submission (port 587, STARTTLS required) ──────────────",
        "submission inet n       -       n       -       -       smtpd",
        "  -o syslog_name=postfix/submission",
        "  -o smtpd_tls_security_level=encrypt",
        "  -o smtpd_sasl_auth_enable=yes",
        "  -o smtpd_tls_auth_only=yes",
        '  -o smtpd_reject_unlisted_recipient=no',
        "  -o smtpd_client_restrictions=permit_sasl_authenticated,reject",
        "  -o milter_macro_daemon_name=ORIGINATING",
        "",
        "# ── SMTPS (port 465, implicit TLS) ────────────────────────",
        "smtps     inet  n       -       n       -       -       smtpd",
        "  -o syslog_name=postfix/smtps",
        "  -o smtpd_tls_wrappermode=yes",
        "  -o smtpd_sasl_auth_enable=yes",
        '  -o smtpd_reject_unlisted_recipient=no',
        "  -o smtpd_client_restrictions=permit_sasl_authenticated,reject",
        "  -o milter_macro_daemon_name=ORIGINATING",
        "",
        "# ── Postscreen (pre-queue on port 25) ─────────────────────",
        "127.0.0.1:12525 inet n  n       y       -       -       postscreen",
        "  -o syslog_name=postfix/postscreen",
        "  -o postscreen_cache_map=btree:${data_directory}/postscreen_cache",
        "",
        "# ── Internal services ──────────────────────────────────────",
        "pickup    fifo  n       -       y       60      1       pickup",
        "cleanup   unix  n       -       y       -       0       cleanup",
        "qmgr      fifo  n       -       n       300     1       qmgr",
        "rewrite   unix  -       -       y       -       -       trivial-rewrite",
        "bounce    unix  -       -       y       -       0       bounce",
        "defer     unix  -       -       y       -       0       bounce",
        "trace     unix  -       -       y       -       0       bounce",
        "verify    unix  -       -       y       -       1       verify",
        "flush     unix  n       -       y       1000?   0       flush",
        "proxymap  unix  -       -       n       -       -       proxymap",
        "smtp      unix  -       -       y       -       -       smtp",
        "relay     unix  -       -       y       -       -       smtp",
        "showq     unix  n       -       y       -       -       showq",
        "error     unix  -       -       y       -       -       error",
        "retry     unix  -       -       y       -       -       error",
        "discard   unix  -       -       y       -       -       discard",
        "lmtp      unix  -       -       y       -       -       lmtp",
        "anvil     unix  -       -       y       -       1       anvil",
        "scache    unix  -       -       y       -       1       scache",
        "",
        "# ── Dovecot LMTP delivery ─────────────────────────────────",
        "dovecot   unix  -       n       n       -       -       pipe",
        "  flags=DRhu user=vmail argv=/usr/lib/dovecot/deliver",
        '  -f ${sender} -d ${recipient}',
        "",
    ]
    return "\n".join(lines) + "\n"


# ── Dovecot config ────────────────────────────────────────────────────────


def render_dovecot_conf(profile: SetupProfile) -> str:
    """Generate /etc/dovecot/dovecot.conf.

    Configures:
      - IMAPS on port 993 (no cleartext IMAP)
      - LMTP for Postfix delivery
      - Virtual mailboxes in /var/mail/%d/%n
      - SASL auth for Postfix
      - Sieve for server-side filtering
    """
    return f"""# KTC Mail — Dovecot config
# Generated by ktc-mail config-renderer. DO NOT EDIT MANUALLY.
# Source: {profile.domain}

# ── Protocols ──────────────────────────────────────────────
protocols = imap lmtp sieve

# ── Listen ─────────────────────────────────────────────────
listen = *

# ── Base directory ─────────────────────────────────────────
base_dir = /var/run/dovecot/

# ── Authentication ─────────────────────────────────────────
auth_username_format = %Lu
auth_mechanisms = plain login

# PAM auth for system users (admin access)
userdb {{
  driver = passwd
}}

# Virtual mailbox auth via passwd-file
passdb {{
  driver = passwd-file
  args = /etc/dovecot/passwd
}}

userdb {{
  driver = static
  args = uid=vmail gid=vmail home=/var/mail/%d/%n
}}

# SASL for Postfix
service auth {{
  unix_listener /var/spool/postfix/private/auth {{
    mode = 0660
    user = postfix
    group = postfix
  }}
  unix_listener auth-userdb {{
    mode = 0600
    user = vmail
  }}
}}

# ── TLS ────────────────────────────────────────────────────
ssl = required
ssl_cert = </etc/letsencrypt/live/ktc-mail/fullchain.pem
ssl_key = </etc/letsencrypt/live/ktc-mail/privkey.pem
ssl_min_protocol = TLSv1.2
ssl_cipher_list = ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384
ssl_prefer_server_ciphers = yes

# ── Mail location ──────────────────────────────────────────
mail_location = maildir:/var/mail/%d/%n
mail_privileged_group = mail
mail_access_groups = vmail

# ── Namespaces ─────────────────────────────────────────────
namespace inbox {{
  inbox = yes
  separator = /
  mailbox Drafts {{
    auto = subscribe
    special_use = \\Drafts
  }}
  mailbox Junk {{
    auto = subscribe
    special_use = \\Junk
  }}
  mailbox Trash {{
    auto = subscribe
    special_use = \\Trash
  }}
  mailbox Sent {{
    auto = subscribe
    special_use = \\Sent
  }}
}}

# ── LMTP (delivery from Postfix) ───────────────────────────
service lmtp {{
  unix_listener /var/spool/postfix/private/dovecot-lmtp {{
    mode = 0600
    user = postfix
    group = postfix
  }}
}}

# ── IMAPS (port 993 only — no cleartext) ───────────────────
service imap-login {{
  inet_listener imap {{
    port = 0  # disabled
  }}
  inet_listener imaps {{
    port = 993
    ssl = yes
  }}
}}

# ── Sieve (server-side filtering) ─────────────────────────
plugin {{
  sieve = /var/mail/%d/%n/.dovecot.sieve
  sieve_default = /var/lib/dovecot/sieve/default.sieve
  sieve_dir = /var/mail/%d/%n/sieve
}}

protocol lda {{
  mail_plugins = $mail_plugins sieve
}}

protocol lmtp {{
  mail_plugins = $mail_plugins sieve
}}

# ── Service config ─────────────────────────────────────────
service imap {{
  process_limit = 256
  client_limit = 1
}}

# ── Logging ────────────────────────────────────────────────
auth_verbose = yes
auth_verbose_passwords = sha1
mail_debug = no
"""


# ── Rspamd config ────────────────────────────────────────────────────────


def render_rspamd_worker_conf(profile: SetupProfile) -> str:
    """Generate rspamd local.d/worker-proxy.inc (milter mode).

    Written to /etc/rspamd/local.d/worker-proxy.inc — merges with the
    default rspamd_proxy worker defined in rspamd.conf.
    The named upstream block matches the default upstream "local" syntax.
    """
    return f"""# KTC Mail — Rspamd proxy worker override
# Generated by ktc-mail config-renderer. DO NOT EDIT MANUALLY.
# Written to local.d/worker-proxy.inc — merges with the default
# rspamd_proxy worker defined in rspamd.conf.

# Spawn 4 milter workers instead of the default 1
count = 4;

# Self-scan mode: the proxy worker itself runs the spam scanner
# instead of forwarding to a separate rspamd instance
upstream "local" {{
  default = yes;
  self_scan = yes;
}}
"""


def render_rspamd_controller_conf(profile: SetupProfile) -> str:
    """Generate rspamd local.d/worker-controller.inc.

    Merges with the default controller worker to restrict admin
    access to localhost only.
    """
    return f"""# KTC Mail — Rspamd controller worker override
# Generated by ktc-mail config-renderer. DO NOT EDIT MANUALLY.

secure_ip = "127.0.0.1";
"""


def render_rspamd_local_conf(profile: SetupProfile) -> str:
    """Generate /etc/rspamd/local.d/ settings."""
    return f"""# KTC Mail — Rspamd local config
# Generated by ktc-mail config-renderer. DO NOT EDIT MANUALLY.

# ── DKIM signing ───────────────────────────────────────────
dkim {{
  sign_alg = rsa-sha256;
  canonicalization = relaxed/simple;
  path = "/etc/ktc-mail/dkim/${{selector}}.private";
  selector = "default";
  domain {{
    {profile.domain} {{
      path = "/etc/ktc-mail/dkim/default.private";
      selector = "default";
    }}
  }}
}}

# ── Classifier ─────────────────────────────────────────────
classifier {{
  bayes {{
    backend = "redis";
    servers = "localhost:6379";
    min_learns = 200;
  }}
}}

# ── Redis ──────────────────────────────────────────────────
redis {{
  servers = "localhost:6379";
}}

# ── Milter headers ─────────────────────────────────────────
milter {{
  rcpt = true;
  header = true;
  greylisting = true;
}}
"""


def render_rspamd_dkim_signing_conf(profile: SetupProfile) -> str:
    """Generate /etc/rspamd/local.d/dkim_signing.conf."""
    return f"""# KTC Mail — DKIM signing config
# Generated by ktc-mail config-renderer. DO NOT EDIT MANUALLY.

allow_username_mismatch = true;
sign_authenticated = true;
sign_local = true;

domain {{
  {profile.domain} {{
    path = "/etc/ktc-mail/dkim/default.private";
    selector = "default";
  }}
}}
"""


# ── Nginx vhost ──────────────────────────────────────────────────────────


def render_nginx_webmail_vhost(profile: SetupProfile) -> str:
    """Generate Nginx vhost for webmail and admin endpoints.

    Proxies to the webmail backend (port 5085 default).
    Serves ACME webroot for HTTP-01 challenges when enabled.
    """
    acme_location = ""
    if profile.certificate_mode == "http-01":
        acme_location = """
    location /.well-known/acme-challenge/ {
        root /var/lib/ktc-mail/acme-webroot;
    }
"""

    return f"""# KTC Mail — Nginx vhost (webmail + admin)
# Generated by ktc-mail config-renderer. DO NOT EDIT MANUALLY.

server {{
    listen 80;
    listen [::]:80;
    server_name {profile.hostname} {profile.webmail_host} {profile.admin_host};
    return 301 https://$server_name$request_uri;
}}

server {{
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {profile.webmail_host};

    ssl_certificate /etc/letsencrypt/live/ktc-mail/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ktc-mail/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers on;

    client_max_body_size 50M;

    location / {{
        proxy_pass http://127.0.0.1:5085;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}
}}

server {{
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {profile.admin_host};

    ssl_certificate /etc/letsencrypt/live/ktc-mail/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ktc-mail/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers on;

    location / {{
        proxy_pass http://127.0.0.1:5085;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}
}}
"""


# ── Autoconfig / Autodiscover XML templates ──────────────────────────────


def render_thunderbird_autoconfig_xml(profile: SetupProfile) -> str:
    """Generate Mozilla autoconfig XML for Thunderbird.

    Served at https://autoconfig.{domain}/mail/config-v1.1.xml
    """
    hostname = profile.hostname
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<clientConfig version="1.1">
  <emailProvider id="{profile.domain}">
    <domain>{profile.domain}</domain>
    <displayName>{profile.domain} Mail</displayName>
    <displayShortName>{profile.domain}</displayShortName>

    <incomingServer type="imap">
      <hostname>{hostname}</hostname>
      <port>993</port>
      <socketType>SSL</socketType>
      <username>%EMAILADDRESS%</username>
      <authentication>password-cleartext</authentication>
    </incomingServer>

    <outgoingServer type="smtp">
      <hostname>{hostname}</hostname>
      <port>587</port>
      <socketType>STARTTLS</socketType>
      <username>%EMAILADDRESS%</username>
      <authentication>password-cleartext</authentication>
    </outgoingServer>

    <documentation url="https://{profile.admin_host}/help/">
      <descr lang="en">KTC Mail setup guide</descr>
    </documentation>
  </emailProvider>
</clientConfig>
"""


def render_outlook_autodiscover_xml(profile: SetupProfile) -> str:
    """Generate Outlook autodiscover XML.

    Served at https://autodiscover.{domain}/autodiscover/autodiscover.xml
    """
    hostname = profile.hostname
    return f"""<?xml version="1.0" encoding="utf-8"?>
<Autodiscover xmlns="http://schemas.microsoft.com/exchange/autodiscover/responseschema/2006">
  <Response xmlns="http://schemas.microsoft.com/exchange/autodiscover/outlook/responseschema/2006a">
    <User>
      <DisplayName>{profile.domain} Mail</DisplayName>
    </User>
    <Account>
      <AccountType>email</AccountType>
      <Action>settings</Action>
      <Protocol>
        <Type>IMAP</Type>
        <Server>{hostname}</Server>
        <Port>993</Port>
        <DomainRequired>off</DomainRequired>
        <LoginName>%EMAILADDRESS%</LoginName>
        <SPA>off</SPA>
        <SSL>on</SSL>
        <AuthRequired>on</AuthRequired>
      </Protocol>
      <Protocol>
        <Type>SMTP</Type>
        <Server>{hostname}</Server>
        <Port>587</Port>
        <DomainRequired>off</DomainRequired>
        <LoginName>%EMAILADDRESS%</LoginName>
        <SPA>off</SPA>
        <SSL>on</SSL>
        <AuthRequired>on</AuthRequired>
        <UsePOPAuth>off</UsePOPAuth>
        <SMTPLast>off</SMTPLast>
      </Protocol>
    </Account>
  </Response>
</Autodiscover>
"""


# ── Combined renderer ────────────────────────────────────────────────────


RENDERED_FILES: dict[str, tuple[str, str, int]] = {
    "postfix/main.cf": (
        "Postfix main configuration",
        "render_postfix_main_cf",
        0o644,
    ),
    "postfix/master.cf": (
        "Postfix master process configuration",
        "render_postfix_master_cf",
        0o644,
    ),
    "dovecot/dovecot.conf": (
        "Dovecot IMAP/LMTP configuration",
        "render_dovecot_conf",
        0o644,
    ),
    "rspamd/local.d/worker-proxy.inc": (
        "Rspamd milter worker override (merges with default rspamd_proxy)",
        "render_rspamd_worker_conf",
        0o644,
    ),
    "rspamd/local.d/worker-controller.inc": (
        "Rspamd controller worker override (restrict admin to localhost)",
        "render_rspamd_controller_conf",
        0o644,
    ),
    "rspamd/local.d/dkim_signing.conf": (
        "Rspamd DKIM signing config",
        "render_rspamd_dkim_signing_conf",
        0o644,
    ),
    "rspamd/local.d/options.conf": (
        "Rspamd local options",
        "render_rspamd_local_conf",
        0o644,
    ),
    "nginx/webmail.conf": (
        "Nginx vhost for webmail + admin",
        "render_nginx_webmail_vhost",
        0o644,
    ),
    "autoconfig/thunderbird.xml": (
        "Mozilla Thunderbird autoconfig XML",
        "render_thunderbird_autoconfig_xml",
        0o644,
    ),
    "autoconfig/outlook.xml": (
        "Microsoft Outlook autodiscover XML",
        "render_outlook_autodiscover_xml",
        0o644,
    ),
}


def render_all(profile: SetupProfile) -> dict[str, str]:
    """Render all mail stack configuration files.

    Returns a dict of relative_path → config_content.
    The caller decides where to write them.
    """
    result: dict[str, str] = {}
    for relpath, (_desc, func_name, _mode) in RENDERED_FILES.items():
        render_fn = globals()[func_name]
        result[relpath] = render_fn(profile)
    return result


def write_all(
    profile: SetupProfile,
    dest: Path | str = Path("/etc"),
    dry_run: bool = False,
) -> dict[str, Path]:
    """Write all rendered config files under dest/.

    Args:
        profile: The setup profile to render.
        dest: Root directory (default /etc — for real deployment).
        dry_run: Print paths instead of writing.

    Returns:
        Dict of relative_path → absolute Path for written files.
    """
    dest = Path(dest)
    rendered = render_all(profile)
    written: dict[str, Path] = {}

    for relpath, content in rendered.items():
        full_path = dest / relpath
        if dry_run:
            print(f"dry-run: {full_path} ({len(content)} bytes)")
            written[relpath] = full_path
            continue
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content, encoding="utf-8")
        written[relpath] = full_path

    return written


# ── DKIM key generation ──────────────────────────────────────────────────


def dkim_generate(
    domain: str,
    selector: str = "default",
    bits: int = 2048,
) -> tuple[bytes, str]:
    """Generate DKIM keypair and DNS record.

    Shells out to openssl — the canonical tool for RSA key generation.
    No Python crypto library dependency. No reimplementation of RSA.

    Returns:
        (private_key_pem, dns_txt_record_string)

    The private key is returned as PEM bytes — caller decides where to
    write it. The DNS record is a ready-to-publish TXT value.
    """
    priv = subprocess.run(
        ["openssl", "genrsa", str(bits)],
        capture_output=True, check=True,
    ).stdout

    pub_der = subprocess.run(
        ["openssl", "rsa", "-pubin", "-outform", "DER"],
        input=subprocess.run(
            ["openssl", "rsa", "-pubout"],
            input=priv, capture_output=True, check=True,
        ).stdout,
        capture_output=True, check=True,
    ).stdout

    b64 = base64.b64encode(pub_der).decode()
    record = f"v=DKIM1; k=rsa; p={b64}"
    return priv, record


def dkim_write(args: argparse.Namespace) -> int:
    """CLI handler for `ktc-mail dkim generate`."""
    from .config import DKIM_DIR, read_json, SetupProfile

    data = read_json(args.config)
    profile = SetupProfile.from_dict(data)
    selector = args.selector

    priv_pem, dns_record = dkim_generate(profile.domain, selector)

    if args.dry_run:
        print(f"dry-run: would write key to {DKIM_DIR / selector}.private")
        print(f"dry-run: DNS TXT \"{selector}._domainkey.{profile.domain}\"")
        print(dns_record)
        return 0

    path = DKIM_DIR / f"{selector}.private"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(priv_pem)
    path.chmod(0o600)

    print(f"wrote: {path}")
    print()
    print(f"DNS TXT record for {selector}._domainkey.{profile.domain}:")
    print(dns_record)
    return 0


# ── MTA-STS policy file ──────────────────────────────────────────────────


def render_mta_sts_policy(profile: SetupProfile) -> str:
    """Generate MTA-STS policy file.

    Served at https://mta-sts.{domain}/.well-known/mta-sts.txt
    """
    return f"""version: STSv1
mode: enforce
mx: {profile.hostname}
max_age: 604800
"""


# ── CLI entry point ──────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(
        description="KTC Mail config renderer (Phase 3)",
    )
    parser.add_argument(
        "command",
        choices=("render", "write"),
        help="render=print to stdout, write=deploy to /etc",
    )
    parser.add_argument("--config", type=Path, default=SETUP_PATH)
    parser.add_argument("--dest", type=Path, default=Path("/etc"))
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would be written")
    args = parser.parse_args()

    try:
        if not args.config.exists():
            print(f"setup profile not found: {args.config}", file=sys.stderr)
            return 1

        data = read_json(args.config)
        profile = SetupProfile.from_dict(data)

        if args.command == "render":
            rendered = render_all(profile)
            for relpath, content in rendered.items():
                print(f"# {'=' * 60}")
                print(f"# {relpath}")
                print(f"# {'=' * 60}")
                print(content, end="")
            return 0

        if args.command == "write":
            written = write_all(profile, dest=args.dest, dry_run=args.dry_run)

            # Also write MTA-STS
            mta_sts = render_mta_sts_policy(profile)
            sts_path = args.dest / "nginx/mta-sts.txt"
            if args.dry_run:
                print(f"dry-run: {sts_path}")
            else:
                sts_path.parent.mkdir(parents=True, exist_ok=True)
                sts_path.write_text(mta_sts, encoding="utf-8")
                written["nginx/mta-sts.txt"] = sts_path

            if args.dry_run:
                return 0

            count = len(written)
            print(f"wrote {count} config files under {args.dest}")
            for relpath, path in sorted(written.items()):
                print(f"  {path}")
            return 0

        return 1

    except Exception as exc:
        print(f"config error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
