#!/usr/bin/env python3
"""KTC Mail — Fail2ban jail configuration (Phase 4 deliverable).

Generates /etc/fail2ban/jail.d/ktc-mail.conf with pre-configured
jails for Postfix SMTP AUTH, Dovecot IMAP/POP3, and Rspamd.

Also provides an optional CrowdSec enrollment helper.

Design rules:
  - Debian/Ubuntu default filter files are referenced, not duplicated.
  - Sensible ban times (escalating: 1h → 1d → 1w → perm).
  - Custom recidive jail re-bans IPs that keep coming back.
  - All jails use nftables-multiport action by default (modern).
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path
from typing import Any

from .config import CONFIG_DIR, SETUP_PATH, SecurityPolicy, read_json

# ── Paths ───────────────────────────────────────────────────────────────

FAIL2BAN_JAIL_DIR = Path("/etc/fail2ban/jail.d")
FAIL2BAN_CONFIG_PATH = FAIL2BAN_JAIL_DIR / "ktc-mail.conf"
FAIL2BAN_FILTER_DIR = Path("/etc/fail2ban/filter.d")
FAIL2BAN_ACTION_DIR = Path("/etc/fail2ban/action.d")

# ── Template ────────────────────────────────────────────────────────────


def render_fail2ban_jails(
    domain: str,
    admin_email: str = "",
    maxretry: int = 3,
    findtime: int = 600,
    bantime: int = 3600,
    action: str = "nftables-multiport",
) -> str:
    """Generate /etc/fail2ban/jail.d/ktc-mail.conf content.

    Args:
        domain: The mail domain (used in ignoreregex for legitimate traffic).
        admin_email: Where to send ban notifications (optional).
        maxretry: Failures before ban (default 3).
        findtime: Window in seconds (default 600 = 10 min).
        bantime: Initial ban duration (default 3600 = 1 hour).
        action: Fail2ban action (default nftables-multiport).

    Returns:
        The complete jail.local file content.
    """
    admin_email = admin_email or "root"

    # ── Log paths — Debian/Ubuntu defaults ─────────────────────────────
    # Postfix/Dovecot log to mail.log; Rspamd has its own log
    mail_log = "/var/log/mail.log"
    rspamd_log = "/var/log/rspamd/rspamd.log"

    # ── Ignore local traffic ───────────────────────────────────────────
    # Don't ban our own public IP or trusted ranges
    ignoreip = [
        "127.0.0.1/8",
        "::1/128",
    ]

    # ── Build jails ────────────────────────────────────────────────────
    lines = [
        "# KTC Mail — Fail2ban jails",
        "# Generated by ktc-mail fail2ban. DO NOT EDIT MANUALLY.",
        "",
        "# ── Global defaults ─────────────────────────────────────────",
        "[DEFAULT]",
        f'ignoreip = {" ".join(ignoreip)}',
        f"bantime = {bantime}",
        f"findtime = {findtime}",
        f"maxretry = {maxretry}",
        f"action = {action}",
        f"destemail = {admin_email}",
        "sendername = KTC Mail (Fail2ban)",
        "",
        "# ── Postfix SMTP AUTH ───────────────────────────────────────",
        "# Covers: SASL authentication failures, relay attempts,",
        "# RCPT TO to invalid recipients, HELO/EHLO policy rejections.",
        "[postfix]",
        "enabled = true",
        'port = smtp,ssmtp,submission',
        "filter = postfix[mode=aggressive]",
        f"logpath = {mail_log}",
        f"maxretry = {maxretry}",
        "findtime = 120",  # shorter window for SMTP abuse
        "",
        "# ── Postfix RBL rejections ──────────────────────────────────",
        "# IPs that hit DNSBL rejections are definitely scanners.",
        "[postfix-rbl]",
        "enabled = true",
        "port = smtp,ssmtp,submission",
        "filter = postfix-rbl",
        f"logpath = {mail_log}",
        "maxretry = 1",
        "findtime = 86400",  # 24h window — one strike and you're out
        "",
        "# ── Dovecot IMAP/POP3 auth ──────────────────────────────────",
        "# Covers: IMAP LOGIN failures, POP3 AUTHORIZATION failures.",
        "[dovecot]",
        "enabled = true",
        'port = imap,imaps,pop3,pop3s',
        "filter = dovecot[mode=aggressive]",
        f"logpath = {mail_log}",
        f"maxretry = {maxretry}",
        "findtime = 120",
        "",
        "# ── Rspamd ──────────────────────────────────────────────────",
        "# Covers: Rspamd worker authentication failures.",
        "[rspamd]",
        "enabled = true",
        'port = smtp,ssmtp,submission',
        "filter = rspamd",
        f"logpath = {rspamd_log}",
        "maxretry = 1",
        "findtime = 86400",
        "",
        "# ── Recidive (repeat offenders) ─────────────────────────────",
        "# IPs banned 3+ times get a permanent ban.",
        "[recidive]",
        "enabled = true",
        'port = smtp,ssmtp,imap,imaps,pop3,pop3s',
        "filter = recidive",
        f"logpath = {mail_log}",
        "bantime = -1",  # permanent
        "maxretry = 3",
        "findtime = 604800",  # 1 week window
        "",
        "# ── Nginx auth ──────────────────────────────────────────────",
        "# Covers: Nginx HTTP authentication failures (admin portal).",
        "[nginx-http-auth]",
        "enabled = true",
        'port = http,https',
        "filter = nginx-http-auth",
        "logpath = /var/log/nginx/error.log",
        f"maxretry = {maxretry}",
        "findtime = 120",
        "",
    ]
    return "\n".join(lines)


# ── CrowdSec enrollment ────────────────────────────────────────────────


def render_crowdsec_enrollment(
    domain: str,
    admin_email: str = "",
) -> str:
    """Generate a script that enrolls the server with CrowdSec.

    Returns a bash script that the admin can review and run.

    CrowdSec is optional — fail2ban covers the same ground without
    external dependencies. This script is provided as a convenience
    for users who want the crowd-sourced reputation layer.

    The script:
      1. Installs the CrowdSec agent from the official repo
      2. Enrolls with a local-only setup (no central API by default)
      3. Installs collections for postfix, dovecot, nginx
      4. Starts the service
    """
    return f"""#!/bin/bash
# KTC Mail — CrowdSec enrollment helper
# Generated by ktc-mail fail2ban. REVIEW BEFORE RUNNING.
set -euo pipefail

echo "=== CrowdSec enrollment for {domain} ==="

# 1. Install CrowdSec
if ! command -v cscli &>/dev/null; then
    echo "Installing CrowdSec..."
    curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | bash
    apt-get install -y crowdsec
fi

# 2. Install collections for mail server
cscli collections install crowdsecurity/postfix
cscli collections install crowdsecurity/dovecot
cscli collections install crowdsecurity/nginx

# 3. (Optional) Enroll with central API — uncomment and set your key
# cscli console enroll YOUR_ENROLL_KEY

# 4. Restart CrowdSec
systemctl restart crowdsec

echo "CrowdSec enrolled. Check status: sudo cscli metrics"
echo ""
echo "To view alerts: sudo cscli alerts list"
echo "To view decisions: sudo cscli decisions list"
"""


# ── Inspection ──────────────────────────────────────────────────────────


def check_fail2ban_installed() -> bool:
    """Check if fail2ban is installed on the system."""
    result = subprocess.run(
        ["which", "fail2ban-server"],
        capture_output=True, text=True, check=False,
    )
    return result.returncode == 0


def check_fail2ban_running() -> bool:
    """Check if fail2ban service is active."""
    result = subprocess.run(
        ["systemctl", "is-active", "fail2ban"],
        capture_output=True, text=True, check=False,
    )
    return result.stdout.strip() == "active"


def check_fail2ban_jails() -> list[dict[str, str]]:
    """Query fail2ban-client for active jail status.

    Returns a list of jail dicts with name, status, banned count.
    Returns empty list if fail2ban is not running.
    """
    if not check_fail2ban_running():
        return []

    result = subprocess.run(
        ["fail2ban-client", "status"],
        capture_output=True, text=True, check=False,
    )
    if result.returncode != 0:
        return []

    jails: list[dict[str, str]] = []
    for line in result.stdout.splitlines():
        line = line.strip()
        if line.startswith("|-") or line.startswith("`-"):
            # e.g. "`- Postfix:  Total: 3  Currently banned: 1"
            parts = line.split(":")
            if len(parts) >= 2:
                jail_name = parts[0].strip().lstrip("|-`- ")
                stats = parts[1:] if len(parts) > 1 else []
                jails.append({
                    "name": jail_name,
                    "status": " | ".join(s.strip() for s in stats),
                })
    return jails


# ── IO operations ──────────────────────────────────────────────────────


def write_jail_config(
    domain: str,
    admin_email: str = "",
    dry_run: bool = False,
) -> Path | None:
    """Write the Fail2ban jail config to disk.

    Args:
        domain: Mail domain.
        admin_email: Admin email for notifications.
        dry_run: If True, print path and content instead of writing.

    Returns:
        The Path written to, or None in dry-run mode.
    """
    content = render_fail2ban_jails(domain, admin_email)

    if dry_run:
        print(f"dry-run: would write {FAIL2BAN_CONFIG_PATH}")
        print(f"dry-run: ({len(content)} bytes)")
        print(content)
        return None

    FAIL2BAN_JAIL_DIR.mkdir(parents=True, exist_ok=True)
    tmp = FAIL2BAN_CONFIG_PATH.with_suffix(".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.chmod(0o644)
    tmp.rename(FAIL2BAN_CONFIG_PATH)
    return FAIL2BAN_CONFIG_PATH


def reload_fail2ban() -> bool:
    """Reload Fail2ban configuration.

    Returns True if reload succeeded, False otherwise.
    """
    if not check_fail2ban_installed():
        print("fail2ban: not installed", file=sys.stderr)
        return False

    result = subprocess.run(
        ["fail2ban-client", "reload"],
        capture_output=True, text=True, check=False,
    )
    if result.returncode != 0:
        print(f"fail2ban: reload failed: {result.stderr.strip()}",
              file=sys.stderr)
        return False
    return True


# ── CLI handlers ────────────────────────────────────────────────────────


def cmd_apply(args: argparse.Namespace) -> int:
    """Apply Fail2ban jail configuration."""
    from .config import SetupProfile, read_json

    if not args.config.exists():
        print(f"setup profile not found: {args.config}", file=sys.stderr)
        print("run 'ktc-mail setup' first or use --domain directly",
              file=sys.stderr)
        return 1

    data = read_json(args.config)
    profile = SetupProfile.from_dict(data)

    path = write_jail_config(
        domain=profile.domain,
        admin_email=profile.admin_email,
        dry_run=args.dry_run,
    )
    if args.dry_run:
        return 0

    if path is None:
        return 1

    print(f"wrote: {path}")

    if args.reload:
        if reload_fail2ban():
            print("fail2ban: reloaded")
        else:
            print("fail2ban: reload failed (install fail2ban first?)",
                  file=sys.stderr)
            return 1

    return 0


def cmd_check(args: argparse.Namespace) -> int:
    """Check Fail2ban installation and jail status."""
    installed = check_fail2ban_installed()
    running = check_fail2ban_running()

    config_exists = FAIL2BAN_CONFIG_PATH.exists()

    print(f"fail2ban installed: {'YES' if installed else 'NO'}")
    print(f"fail2ban running:   {'YES' if running else 'NO'}")
    print(f"ktc-mail config:    {'YES' if config_exists else 'NO'}")

    if not installed:
        print()
        print("Install: apt-get install fail2ban")
        return 1

    if config_exists:
        print()
        print(f"Config: {FAIL2BAN_CONFIG_PATH}")

    if running:
        jails = check_fail2ban_jails()
        if jails:
            print()
            print("Active jails:")
            for jail in jails:
                print(f"  {jail['name']}: {jail['status']}")

    return 0 if installed and config_exists else 1


def cmd_crowdsec(args: argparse.Namespace) -> int:
    """Generate or display CrowdSec enrollment script."""
    from .config import SetupProfile, read_json

    if args.domain:
        domain = args.domain
        admin_email = args.admin_email or ""
    elif args.config.exists():
        data = read_json(args.config)
        profile = SetupProfile.from_dict(data)
        domain = profile.domain
        admin_email = profile.admin_email
    else:
        print("provide --domain or run setup first", file=sys.stderr)
        return 1

    script = render_crowdsec_enrollment(domain, admin_email)

    output = Path(args.output) if args.output else None
    if output:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(script, encoding="utf-8")
        output.chmod(0o755)
        print(f"wrote: {output}")
    else:
        print(script)

    return 0


# ── Argparse subcommand builder ─────────────────────────────────────────


def add_subparser(sub) -> None:
    """Add the 'fail2ban' subcommand parser to the CLI."""
    p_f2b = sub.add_parser("fail2ban", help="Fail2ban jail management")
    p_f2b.add_argument(
        "f2b_cmd", choices=("apply", "check", "crowdsec"),
        help="fail2ban apply | check | crowdsec",
    )
    p_f2b.add_argument("--reload", action="store_true",
                       help="Reload fail2ban after applying config")
    p_f2b.add_argument("--domain", default="",
                       help="Domain (for crowdsec without setup profile)")
    p_f2b.add_argument("--admin-email", default="",
                       help="Admin email (for crowdsec)")
    p_f2b.add_argument("--output", default="",
                       help="Write CrowdSec script to path")
    p_f2b.add_argument("--dry-run", action="store_true",
                       help="Preview changes without writing")


def dispatch(args: argparse.Namespace) -> int:
    """Dispatch fail2ban subcommands."""
    dispatch_map = {
        "apply": cmd_apply,
        "check": cmd_check,
        "crowdsec": cmd_crowdsec,
    }
    handler = dispatch_map.get(args.f2b_cmd)
    if handler is None:
        return 1
    return handler(args)
