#!/usr/bin/env python3
"""KTC Mail firewall policy monitor — nftables only.

Reads the setup profile's open_ports, verifies the ``inet ktc_mail``
nftables table has the expected rules, and reports drift.

One ruleset handles both IPv4 and IPv6 via the ``inet`` address family.
The chain default policy is ``drop`` — anything not explicitly allowed
is rejected.

Default allowed ports:
  - 22/tcp  (SSH)
  - 25/tcp  (SMTP)
  - 443/tcp (HTTPS, webmail, admin)
  - 587/tcp (Submission)
  - 993/tcp (IMAPS)
  - 80/tcp  (only if HTTP-01 cert mode)
  - 4190/tcp (ManageSieve, only if enabled)

nftables has been the default firewall on Debian since 10/Buster (2019)
and Ubuntu since 20.04 (2020).  The iptables backend was removed in
Phase 8 — there is no fallback.

See also: ssh_policy.py for SSH-adjacent hardening.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .config import (
    CONFIG_DIR,
    SETUP_PATH,
    SecurityPolicy,
    read_json,
)

NFT_TABLE = "inet ktc_mail"
NFT_CHAIN = "INPUT"
NFT_RULESET_PATH = Path("/etc/nftables/ktc-mail.conf")
DEFAULT_TCP_PORTS = (22, 25, 443, 587, 993)


# ── Data ────────────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class Finding:
    """A single firewall policy violation."""
    source: str = "nftables"
    message: str = ""


# ── Helpers ─────────────────────────────────────────────────────────────────


def _run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, text=True, capture_output=True, check=False)


def load_policy(config_path: Path) -> SecurityPolicy:
    """Load the security policy from the setup profile.

    Falls back to safe defaults if the profile doesn't exist.
    """
    if not config_path.exists():
        return SecurityPolicy()
    try:
        data = read_json(config_path)
        policy_data = data.get("security", {})
        # Backward compat: also check top-level open_ports
        if "open_ports" in data and "ports_open" not in policy_data:
            policy_data["ports_open"] = data["open_ports"]
        return SecurityPolicy.from_dict(policy_data)
    except (OSError, ValueError, json.JSONDecodeError):
        return SecurityPolicy()


def _nft_available() -> bool:
    """Return True if the nft binary is on $PATH."""
    return _run(["which", "nft"]).returncode == 0


def _chain_exists() -> bool:
    """Check whether our nftables table + chain already exist."""
    return _run(["nft", "list", "chain", NFT_TABLE, NFT_CHAIN]).returncode == 0


def _create_chain() -> None:
    """Create the nftables table and INPUT chain from scratch.

    Idempotent: safe to call if the table already exists (``nft add
    table`` is a no-op for existing tables, and ``nft create chain``
    will fail harmlessly if the chain already exists — but we only
    call this when ``_chain_exists()`` returned False).
    """
    _run(["nft", "add", "table", "inet", NFT_TABLE])
    _run(["nft", "add", "chain", "inet", NFT_TABLE, NFT_CHAIN,
          "{", "type", "filter", "hook", "input",
          "priority", "0;", "policy", "drop;", "}"])


# ── Ruleset generation ──────────────────────────────────────────────────────


def generate_ruleset(ports: list[int]) -> str:
    """Generate a complete nftables ruleset.

    The output is a self-contained ``nft -f`` script that:
      1. Ensures the table exists (idempotent ``add table``)
      2. Ensures the chain exists with drop policy
      3. Flushes stale rules from the chain
      4. Adds the current port rules

    ``nft -f`` applies the whole file atomically — there is no window
    where the chain is empty.
    """
    port_set = ", ".join(str(p) for p in sorted(ports))

    return f"""#!/usr/sbin/nft -f
# KTC Mail — nftables ruleset
# Generated by ktc-mail firewall. DO NOT EDIT MANUALLY.
# {NFT_TABLE} / {NFT_CHAIN}

add table {NFT_TABLE}
add chain {NFT_TABLE} {NFT_CHAIN} {{ type filter hook input priority 0; policy drop; }}
flush chain {NFT_TABLE} {NFT_CHAIN}

# Allow established connections
add rule {NFT_TABLE} {NFT_CHAIN} ct state established,related accept

# Allow loopback
add rule {NFT_TABLE} {NFT_CHAIN} iif lo accept

# Allowed TCP ports
add rule {NFT_TABLE} {NFT_CHAIN} tcp dport {{ {port_set} }} accept
"""


# ── Inspection ──────────────────────────────────────────────────────────────


def inspect(required_ports: list[int]) -> list[Finding]:
    """Compare live nftables rules against the expected set.

    Returns a list of ``Finding`` for every missing rule or policy
    violation.  Returns a single Finding if the chain doesn't exist
    at all.
    """
    if not _nft_available():
        return [Finding(message="nft binary not found on $PATH")]

    if not _chain_exists():
        return [Finding(message=f"chain {NFT_TABLE} {NFT_CHAIN} does not exist")]

    result = _run(["nft", "list", "chain", NFT_TABLE, NFT_CHAIN])
    rules_output = result.stdout
    findings: list[Finding] = []

    if "ct state established,related accept" not in rules_output:
        findings.append(Finding(message="missing: ct state established,related accept"))
    if "iif lo accept" not in rules_output and 'iif "lo" accept' not in rules_output:
        findings.append(Finding(message="missing: iif lo accept"))

    for port in sorted(required_ports):
        if f"tcp dport {port} accept" not in rules_output:
            findings.append(Finding(message=f"missing: tcp dport {port} accept"))

    if "policy drop" not in rules_output:
        findings.append(Finding(message="chain policy is not drop"))

    return findings


# ── Enforcement ─────────────────────────────────────────────────────────────


def enforce(required_ports: list[int]) -> None:
    """Apply the nftables ruleset atomically.

    Uses ``nft -f`` with the generated ruleset.  The ruleset itself
    handles first-run vs. update via idempotent ``add table`` /
    ``add chain`` commands, so there is no special first-run path.

    The ruleset file is written atomically (tempfile + rename) so that
    a crash mid-write cannot produce a partial file.
    """
    ports = sorted(required_ports)
    ruleset = generate_ruleset(ports)

    NFT_RULESET_PATH.parent.mkdir(parents=True, exist_ok=True)
    tmp = NFT_RULESET_PATH.with_suffix(".tmp")
    tmp.write_text(ruleset, encoding="utf-8")
    tmp.chmod(0o600)
    tmp.rename(NFT_RULESET_PATH)  # atomic on same filesystem

    result = _run(["nft", "-f", str(NFT_RULESET_PATH)])
    if result.returncode != 0:
        print(f"nftables: error applying ruleset: {result.stderr.strip()}",
              file=sys.stderr)
        # On first-run on very old nftables, add may fail for table that
        # already was created implicitly.  Fall through — we still report
        # the inspection findings below.
        return

    # Verify and count
    result = _run(["nft", "list", "chain", NFT_TABLE, NFT_CHAIN])
    rule_count = sum(
        1 for l in result.stdout.splitlines()
        if l.strip() and not l.strip().startswith("#")
        and not l.strip().startswith("table")
        and not l.strip().startswith("chain")
        and not l.strip().startswith("}")
    )
    print(f"nftables: {NFT_TABLE}/{NFT_CHAIN} — {rule_count} rules")


# ── CLI entry point ─────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Check or enforce KTC Mail nftables firewall policy",
    )
    parser.add_argument(
        "--enforce", action="store_true",
        help="Recreate nftables rules before checking",
    )
    parser.add_argument(
        "--config", type=Path, default=SETUP_PATH,
        help="KTC Mail setup profile path",
    )
    args = parser.parse_args()

    if not _nft_available():
        print("firewall: nft binary not found (install nftables)", file=sys.stderr)
        return 2

    try:
        policy = load_policy(args.config)
    except Exception as exc:
        print(f"firewall: cannot load config: {exc}", file=sys.stderr)
        return 2

    ports = policy.actual_open_ports

    if args.enforce:
        enforce(ports)

    findings = inspect(ports)
    for f in findings:
        print(f"firewall: {f.message}", file=sys.stderr)

    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
