#!/usr/bin/env python3
"""KTC Mail — Postfix policy daemon for per-user outbound rate limiting.

Implements the Postfix SMTPD policy protocol:
  https://www.postfix.org/SMTPD_POLICY_README.html

Listens on ``127.0.0.1:12345`` (or ``KTC_RATE_PORT``), reads policy
requests from Postfix, checks per-user (SASL-authenticated) send rates
against configured limits, and returns ``OK`` or ``DEFER_IF_PERMIT``.

Rate state is kept in memory — on restart, counters reset.  This is
intentional: a restart means the daemon is (briefly) unavailable and
Postfix will defer messages that can't be checked, which is safer than
allowing unlimited sending during daemon downtime.

Design:
  - Single-threaded with ``select`` for I/O (no thread overhead).
  - One connection per Postfix SMTP session — the protocol exchange
    is quick (one request, one response), so a simple accept loop
    with per-connection synchronous handling is sufficient.
  - Rate data is pruned on every check (O(1) amortised).

Postfix master.cf (auto-generated by config renderer):
  smtp inet ... smtpd
    -o smtpd_recipient_restrictions=...
    -o check_policy_service=inet:127.0.0.1:12345
    ...

Systemd: ktc-mail-rate-limit.service
"""

from __future__ import annotations

import os
import signal
import socket
import sys
import time
from collections import defaultdict

# ── Configuration (from environment, or defaults) ──────────────────────────

LISTEN_ADDR = os.environ.get("KTC_RATE_BIND", "127.0.0.1")
LISTEN_PORT = int(os.environ.get("KTC_RATE_PORT", "12345"))
MAX_PER_HOUR = int(os.environ.get("KTC_RATE_MAX_PER_HOUR", "100"))
MAX_PER_DAY = int(os.environ.get("KTC_RATE_MAX_PER_DAY", "1000"))
BACKLOG = 32
PRUNE_INTERVAL = 300  # purge stale entries every 5 minutes


# ── Logging (lazy-imported to avoid circular deps) ────────────────
# setup_logging is called from main() — not at module level.
_log_setup_done = False


def _ensure_logging() -> None:
    global _log_setup_done
    if not _log_setup_done:
        from .config import setup_logging
        setup_logging()
        _log_setup_done = True


# ── Rate tracker — in-memory, periodic pruning ─────────────────────────────
# Design (H-009 fix): counter-based O(1) per user instead of unbounded lists.
#   {sasl_username: (count, window_start)}
# Memory: O(1) per user, not O(n_events).
#
# H-008 fix: after 3 consecutive rate-limit hits the action escalates
# from DEFER_IF_PERMIT (which fills Postfix's queue) to REJECT (which
# bounces immediately, preventing queue growth).

_ESCALATE_AFTER = 3  # consecutive rate-limit hits → REJECT


class RateTracker:
    """Per-user send rate tracker with sliding windows.

    Counter-based: O(1) memory per user, O(1) time per check.
    """

    def __init__(self) -> None:
        # (count, window_start) per user per window
        self._hourly: dict[str, tuple[int, float]] = {}
        self._daily: dict[str, tuple[int, float]] = {}
        # Consecutive rate-limit denials per user (H-008 escalation)
        self._consecutive: dict[str, int] = {}
        self._last_prune: float = 0.0

    @staticmethod
    def _check_counter(
        entry: tuple[int, float] | None,
        limit: int,
        window: float,
        now: float,
    ) -> tuple[bool, tuple[int, float]]:
        """Check if *entry* is within *limit/*window*.

        Returns (over_limit, updated_entry).
        """
        if entry is None or now - entry[1] > window:
            # Window expired — reset
            return False, (0, now)
        count, _ = entry
        if count >= limit:
            return True, entry
        return False, entry

    def check_and_track(self, username: str) -> str:
        """Check rates for *username*, record this attempt, return a
        Postfix policy action string.

        Returns ``action=OK`` if within limits, or
        ``action=DEFER_IF_PERMIT`` / ``action=REJECT`` with a reason
        string if over (escalates to REJECT after 3 consecutive hits).
        """
        now = time.monotonic()

        # ── Hourly check ───────────────────────────────────────────────
        over_h, h_entry = self._check_counter(
            self._hourly.get(username), MAX_PER_HOUR, 3600.0, now)
        if over_h:
            return self._deny(username, f"{MAX_PER_HOUR}/hour")

        # ── Daily check ────────────────────────────────────────────────
        over_d, d_entry = self._check_counter(
            self._daily.get(username), MAX_PER_DAY, 86400.0, now)
        if over_d:
            return self._deny(username, f"{MAX_PER_DAY}/day")

        # ── Record (increment counters) ─────────────────────────────────
        self._hourly[username] = (h_entry[0] + 1, h_entry[1])
        self._daily[username] = (d_entry[0] + 1, d_entry[1])
        # Clear consecutive denials on success
        self._consecutive.pop(username, None)

        return "action=OK"

    def _deny(self, username: str, limit_label: str) -> str:
        """Return a deny action, escalating to REJECT after repeated hits.

        H-008: DEFER_IF_PERMIT fills Postfix's queue. After 3 consecutive
        rate-limit hits, return REJECT to bounce immediately.
        """
        count = self._consecutive.get(username, 0) + 1
        self._consecutive[username] = count

        if count >= _ESCALATE_AFTER:
            return (
                f"action=REJECT "
                f"rate limit exceeded ({limit_label}) — repeated violation"
            )
        return (
            f"action=DEFER_IF_PERMIT "
            f"rate limit exceeded ({limit_label})"
        )

    def prune(self) -> None:
        """Remove stale entries for ALL users.  Called periodically."""
        now = time.monotonic()

        # Prune hourly tracker
        stale_h = [
            u for u, (_, ws) in self._hourly.items()
            if now - ws > 3600.0
        ]
        for u in stale_h:
            del self._hourly[u]

        # Prune daily tracker
        stale_d = [
            u for u, (_, ws) in self._daily.items()
            if now - ws > 86400.0
        ]
        for u in stale_d:
            del self._daily[u]

        # Prune consecutive-denial tracker (clear entries older than 1h)
        stale_c = [
            u for u, c in self._consecutive.items()
            if c == 0
        ]
        for u in stale_c:
            del self._consecutive[u]

        self._last_prune = now


# ── Postfix policy protocol handler ────────────────────────────────────────


def handle_client(tracker: RateTracker, conn: socket.socket) -> None:
    """Handle one policy protocol exchange over *conn*.

    The Postfix policy protocol is a single-request-per-connection
    protocol: Postfix connects, sends one request (key=value pairs
    terminated by blank line), and reads one response (action=...).
    """
    request: dict[str, str] = {}
    data = b""

    try:
        while True:
            chunk = conn.recv(4096)
            if not chunk:
                break
            data += chunk

            # Process complete requests
            while True:
                idx = data.find(b"\n\n")
                if idx == -1:
                    break
                raw = data[:idx]
                data = data[idx + 2:]

                # Parse request attributes
                for line in raw.decode("utf-8", errors="replace").splitlines():
                    line = line.strip()
                    if "=" in line:
                        k, v = line.split("=", 1)
                        request[k.strip()] = v.strip()

                # Make decision
                username = request.get("sasl_username", "")
                if username:
                    decision = tracker.check_and_track(username)
                else:
                    decision = "action=OK"  # unauthenticated: pass through

                conn.sendall((decision + "\n\n").encode())
                request = {}

    except (ConnectionError, OSError, TimeoutError):
        pass
    finally:
        try:
            conn.close()
        except OSError:
            pass


# ── Daemon entry point ─────────────────────────────────────────────────────


def main() -> int:
    _ensure_logging()
    listen_addr = LISTEN_ADDR
    listen_port = LISTEN_PORT
    tracker = RateTracker()
    last_prune_check: float = 0.0

    # M-06: Subscribe to SIGTERM so `systemctl stop ktc-mail-rate-limit`
    # actually terminates the process instead of silently continuing.
    _shutdown = False

    def _on_sigterm(sig: int, frame: object) -> None:  # noqa: ANN401
        nonlocal _shutdown
        _shutdown = True

    signal.signal(signal.SIGTERM, _on_sigterm)

    # Create socket
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    try:
        sock.bind((listen_addr, listen_port))
        sock.listen(BACKLOG)
    except OSError as exc:
        print(f"rate-limiter: cannot bind {listen_addr}:{listen_port}: {exc}",
              file=sys.stderr)
        return 1

    print(f"rate-limiter: listening on {listen_addr}:{listen_port}",
          file=sys.stderr)

    sock.settimeout(1.0)  # periodic wake-up to check _shutdown

    while not _shutdown:
        try:
            conn, addr = sock.accept()
        except TimeoutError:
            continue
        except KeyboardInterrupt:
            print("rate-limiter: shutting down", file=sys.stderr)
            break
        except OSError as exc:
            print(f"rate-limiter: accept error: {exc}", file=sys.stderr)
            continue

        # Periodic pruning (don't block accept for long)
        now = time.monotonic()
        if now - last_prune_check >= PRUNE_INTERVAL:
            tracker.prune()
            last_prune_check = now

        handle_client(tracker, conn)

    sock.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
