#!/usr/bin/env python3
"""KTC Mail — Postfix policy daemon for per-user outbound rate limiting.

Implements the Postfix SMTPD policy protocol:
  https://www.postfix.org/SMTPD_POLICY_README.html

Listens on ``127.0.0.1:12345`` (or ``KTC_RATE_PORT``), reads policy
requests from Postfix, checks per-user (SASL-authenticated) send rates
against configured limits, and returns ``OK`` or ``DEFER_IF_PERMIT``.

Rate state is kept in memory — on restart, counters reset.  This is
intentional: a restart means the daemon is (briefly) unavailable and
Postfix will defer messages that can't be checked, which is safer than
allowing unlimited sending during daemon downtime.

Design:
  - Single-threaded with ``select`` for I/O (no thread overhead).
  - One connection per Postfix SMTP session — the protocol exchange
    is quick (one request, one response), so a simple accept loop
    with per-connection synchronous handling is sufficient.
  - Rate data is pruned on every check (O(1) amortised).

Postfix master.cf (auto-generated by config renderer):
  smtp inet ... smtpd
    -o smtpd_recipient_restrictions=...
    -o check_policy_service=inet:127.0.0.1:12345
    ...

Systemd: ktc-mail-rate-limit.service
"""

from __future__ import annotations

import os
import socket
import sys
import time
from collections import defaultdict

# ── Configuration (from environment, or defaults) ──────────────────────────

LISTEN_ADDR = os.environ.get("KTC_RATE_BIND", "127.0.0.1")
LISTEN_PORT = int(os.environ.get("KTC_RATE_PORT", "12345"))
MAX_PER_HOUR = int(os.environ.get("KTC_RATE_MAX_PER_HOUR", "100"))
MAX_PER_DAY = int(os.environ.get("KTC_RATE_MAX_PER_DAY", "1000"))
BACKLOG = 32
PRUNE_INTERVAL = 300  # purge stale entries every 5 minutes


# ── Rate tracker — in-memory, periodic pruning ─────────────────────────────
# Data: {sasl_username: [timestamp, timestamp, ...]}
# Timestamps are added on each accepted send and pruned when they fall
# outside the sliding window.  The dict is never explicitly deleted —
# unused entries are removed lazily during the periodic prune sweep.


class RateTracker:
    """Per-user send rate tracker with sliding windows.

    Thread-safe for CPython due to the GIL (single-threaded use in the
    daemon).  All operations are O(n) in the number of tracked events
    for the user, which is bounded by the rate limit itself.
    """

    def __init__(self) -> None:
        self._hourly: dict[str, list[float]] = defaultdict(list)
        self._daily: dict[str, list[float]] = defaultdict(list)
        self._last_prune: float = 0.0

    def check_and_track(self, username: str) -> str:
        """Check rates for *username*, record this attempt, return a
        Postfix policy action string.

        Returns ``action=OK`` if within limits, or
        ``action=DEFER_IF_PERMIT ...`` with a reason string if over.
        """
        now = time.monotonic()
        hour_ago = now - 3600.0
        day_ago = now - 86400.0

        # ── Hourly check ───────────────────────────────────────────────
        hq = self._hourly[username]
        while hq and hq[0] < hour_ago:
            hq.pop(0)
        if len(hq) >= MAX_PER_HOUR:
            return (
                f"action=DEFER_IF_PERMIT "
                f"rate limit exceeded ({MAX_PER_HOUR}/hour)"
            )

        # ── Daily check ────────────────────────────────────────────────
        dq = self._daily[username]
        while dq and dq[0] < day_ago:
            dq.pop(0)
        if len(dq) >= MAX_PER_DAY:
            return (
                f"action=DEFER_IF_PERMIT "
                f"daily rate limit exceeded ({MAX_PER_DAY}/day)"
            )

        # ── Record ─────────────────────────────────────────────────────
        hq.append(now)
        dq.append(now)

        return "action=OK"

    def prune(self) -> None:
        """Remove stale entries for ALL users.  Called periodically."""
        now = time.monotonic()
        hour_ago = now - 3600.0
        day_ago = now - 86400.0

        # Prune hourly tracker
        empty_h = []
        for user, q in self._hourly.items():
            while q and q[0] < hour_ago:
                q.pop(0)
            if not q:
                empty_h.append(user)
        for user in empty_h:
            del self._hourly[user]

        # Prune daily tracker
        empty_d = []
        for user, q in self._daily.items():
            while q and q[0] < day_ago:
                q.pop(0)
            if not q:
                empty_d.append(user)
        for user in empty_d:
            del self._daily[user]

        self._last_prune = now


# ── Postfix policy protocol handler ────────────────────────────────────────


def handle_client(tracker: RateTracker, conn: socket.socket) -> None:
    """Handle one policy protocol exchange over *conn*.

    The Postfix policy protocol is a single-request-per-connection
    protocol: Postfix connects, sends one request (key=value pairs
    terminated by blank line), and reads one response (action=...).
    """
    request: dict[str, str] = {}
    data = b""

    try:
        while True:
            chunk = conn.recv(4096)
            if not chunk:
                break
            data += chunk

            # Process complete requests
            while True:
                idx = data.find(b"\n\n")
                if idx == -1:
                    break
                raw = data[:idx]
                data = data[idx + 2:]

                # Parse request attributes
                for line in raw.decode("utf-8", errors="replace").splitlines():
                    line = line.strip()
                    if "=" in line:
                        k, v = line.split("=", 1)
                        request[k.strip()] = v.strip()

                # Make decision
                username = request.get("sasl_username", "")
                if username:
                    decision = tracker.check_and_track(username)
                else:
                    decision = "action=OK"  # unauthenticated: pass through

                conn.sendall((decision + "\n\n").encode())
                request = {}

    except (ConnectionError, OSError, TimeoutError):
        pass
    finally:
        try:
            conn.close()
        except OSError:
            pass


# ── Daemon entry point ─────────────────────────────────────────────────────


def main() -> int:
    listen_addr = LISTEN_ADDR
    listen_port = LISTEN_PORT
    tracker = RateTracker()
    last_prune_check: float = 0.0

    # Create socket
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    try:
        sock.bind((listen_addr, listen_port))
        sock.listen(BACKLOG)
    except OSError as exc:
        print(f"rate-limiter: cannot bind {listen_addr}:{listen_port}: {exc}",
              file=sys.stderr)
        return 1

    print(f"rate-limiter: listening on {listen_addr}:{listen_port}",
          file=sys.stderr)

    while True:
        try:
            conn, addr = sock.accept()
        except KeyboardInterrupt:
            print("rate-limiter: shutting down", file=sys.stderr)
            break
        except OSError as exc:
            print(f"rate-limiter: accept error: {exc}", file=sys.stderr)
            continue

        # Periodic pruning (don't block accept for long)
        now = time.monotonic()
        if now - last_prune_check >= PRUNE_INTERVAL:
            tracker.prune()
            last_prune_check = now

        handle_client(tracker, conn)

    sock.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
